indent = 2
margin = 100
always_for_in = true
align_assignment = true
align_struct_field = true
remove_extra_newlines = true
always_use_return = true
import_to_using = true
whitespace_typedefs = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true

