name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: |
          julia --color=yes -e "using Pkg; Pkg.activate("."); Pkg.build()"
          julia --check-bounds=yes --color=yes -e "using Pkg; Pkg.activate("."); Pkg.test(coverage=true)"

